# Generated by Django 2.2.2 on 2019-10-03 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convsort', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 10, 3, 12, 8, 36, 2044)),
        ),
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 10, 3, 12, 8, 36, 2277)),
        ),
    ]
