# Generated by Django 2.2.2 on 2019-10-03 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convsort', '0002_auto_20191003_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 10, 3, 13, 46, 49, 17561)),
        ),
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 10, 3, 13, 46, 49, 17790)),
        ),
    ]
