# Generated by Django 2.2.2 on 2019-10-03 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convsort', '0003_auto_20191003_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 10, 3, 13, 54, 54, 225708)),
        ),
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 10, 3, 13, 54, 54, 225947)),
        ),
    ]
