# Generated by Django 2.2.2 on 2019-10-03 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convsort', '0004_auto_20191003_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='cvs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.datetime(2019, 10, 3, 13, 57, 15, 711773))),
                ('job', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='cv',
        ),
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 10, 3, 13, 57, 15, 711520)),
        ),
    ]
