# Generated by Django 2.2.2 on 2019-10-03 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convsort', '0007_auto_20191003_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvs',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 10, 3, 15, 23, 13, 571970)),
        ),
        migrations.AlterField(
            model_name='cvs',
            name='uid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 10, 3, 15, 23, 13, 571709)),
        ),
    ]
