# Generated by Django 2.2.2 on 2019-10-03 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convsort', '0010_auto_20191003_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvs',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cvs',
            name='path',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 10, 3, 16, 57, 32, 957724)),
        ),
    ]
