# Generated by Django 2.2.2 on 2019-10-09 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convsort', '0013_auto_20191009_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.CharField(default='null', max_length=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 10, 9, 15, 25, 16, 833026)),
        ),
    ]
