# Generated by Django 2.2.2 on 2019-10-09 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convsort', '0015_auto_20191009_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 10, 9, 16, 39, 22, 857464)),
        ),
    ]
