# Generated by Django 2.2.2 on 2019-11-08 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convsort', '0016_auto_20191009_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvs',
            name='jid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 11, 8, 17, 48, 56, 655000)),
        ),
    ]
