# Generated by Django 2.2.2 on 2019-11-08 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convsort', '0019_auto_20191108_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvs',
            name='job',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 11, 8, 18, 43, 8, 222449)),
        ),
    ]
