# Generated by Django 2.2.2 on 2019-11-09 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convsort', '0020_auto_20191108_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 11, 9, 6, 38, 15, 469694)),
        ),
    ]
